
FROM php:8.3-apache

# Install dependencies sistem yang dibutuhkan Laravel
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    git

# Install ekstensi PHP (termasuk PDO untuk MySQL)
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Aktifkan modul rewrite Apache (wajib untuk route Laravel)
RUN a2enmod rewrite

# Set direktori kerja di dalam container
WORKDIR /var/www/html

# Salin seluruh kodingan project ke dalam container
COPY . /var/www/html

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Atur hak akses agar folder storage dan cache bisa ditulis oleh Laravel
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

# Ubah root document Apache ke folder /public milik Laravel
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf